### PR TITLE
InfluxDB backend

### PR DESCRIPTION
**Pull request by kostko**
Adds an InfluxDB backend implementation.

### CODE REVIEW

**Comment by kostko** [comment]
Discovered some issues with the underlying InfluxDB store:
* No apparent way to properly support NULL values in the highest granularity (you cannot insert nulls or NaNs into InfluxDB). For time bucket aggregations, missing values are handled properly (the respective buckets become NULL). See influxdb/influxdb#4089.
* No nice way to properly support certain derivation operators (sum, counter_reset). There is a way to support derivative and to emulate counter_derivative using non_negative_derivative (by always assuming a reset on counter wrap).

Currently, there is also no explicit downsampling, which is instead handled on demand (during query time), but based on quick benchmarks, the queries still perform very well.

cc @mitar

**Comment by kostko** [comment]
I think the derivation operators can be addressed in a similar way to our MongoDB backend. We record all dependencies in the stream metadata and then process all contributions inside datastream. This way we don't depend on any backend store features, we do lose some performance in comparison to handling everything inside InfluxDB, but we can handle arbitrary operators. And when InfluxDB gets a richer InfluxQL, operator implementations can be migrated there.

**Comment by kostko** [comment]
The InfluxDB backend now supports derive operators and uses PostgreSQL as a metadata store.

**Comment by mitar** [comment]
Are all downsampling operators now supported?

**Comment by mitar** [comment]
One more thing, what about numeric precision? For MongoDB we made some efforts to be able to store full values.

**Comment by mitar** [comment]
> by always assuming a reset on counter wrap

That is degradation from our current approach which is more precise. :-(

**Comment by mitar** [comment]
Related ticket about metadata: https://github.com/influxdata/influxdb/issues/5258

**Comment by kostko** [comment]
> Are all downsampling operators now supported?

No, downsampling is limited by the InfluxDB backend. But we support all derive operators.

> One more thing, what about numeric precision?

Not at the moment. You can check the tests to see which ones are shared between both backends.

Note that completely proper handling of NULL values also is not possible until the above InfluxDB issue is addressed (NaN support).

**Comment by kostko** [comment]
> That is degradation from our current approach which is more precise. :-(

No, this is an old comment. The current implementation of derive operators has exactly the same semantics, which are confirmed by exactly the same tests.

**Comment by mitar** [comment]
So only the more limited operators and NULL values are the issue?

What about time operators?

**Comment by kostko** [comment]
> What about time operators?

Those are unfortunately non-existent in InfluxDB. When downsampling, you only get a fixed timestamp representing the start of each bucket, unrelated to any datapoints contained within.

**Comment by mitar** [comment]
Hm, I think we should or open tickets or implement things for missing operators upstream. And then maybe wait before migrating to InfluxDB for the support upstream. Can you document precisely here what are missing features?

**Comment by kostko** [comment]
The major missing features in InfluxDB are:
* Support for NaN (influxdata/influxdb#4089).
* Support for different time aggregation functions (currently the timestamp is always the start of the aggregation bucket regardless of the timestamps of the datapoints it contains).
* It is not possible to make an aggregation if you don't know where the datapoints start in time. The problem is that if you query for example from the beginning of time, then InfluxDB will start returning also all the missing intervals (and return an error if there would be too many). One possible solution is to always first query for the earliest datapoint and then perform the aggregation. But perhaps this could be avoided.

All required value aggregation functions are currently implemented. In the long term it would also be nice to somehow support "derived streams" directly in InfluxDB, together with dependency metadata management (we currently need PostgreSQL for that).

**Comment by kostko** [comment]
I have tested this branch on nodewatcher and fixed some derived stream processing-related performance issues. Preliminary testing shows that it works great (works with django-datastream without changes, which shows that our abstraction is nice). I would include the current InfluxDB backend into datastream 0.5.0. Perhaps some documentation for each backend should be added.

A good thing is that now the API has truly been tested on multiple backends and both current backends share a majority of the test cases.

**Comment by mitar** [comment]
So derivation operators are currently done inside the datastream and not inside InfluxDB?

**Comment by mitar** [comment]
> One possible solution is to always first query for the earliest datapoint and then perform the aggregation.

Previously, we stored the information about the earliest datapoint. Also visualization quite heavily depends on the information about the earliest and latest datapoint. Is this now an extra query every time?

**Comment by mitar** [comment]
Does InfluxDB have some concept of assumed interval? From what you wrote that "InfluxDB will start returning also all the missing interval" seems like that? Because we are [using nulls](https://github.com/influxdata/influxdb/issues/4089#issuecomment-172047541) to differentiate between missing intervals and real nulls? Maybe we should comment that in the ticket?

**Comment by kostko** [comment]
> So derivation operators are currently done inside the datastream and not inside InfluxDB?

Yes.

> Is this now an extra query every time?

Yes, I would like to avoid writing to the PostgreSQL database on every append.

**Comment by mitar** [comment]
> Yes, I would like to avoid writing to the PostgreSQL database on every append.

Does this look like a heavy operation for InfluxDB? To get newest and oldest values?

**Comment by kostko** [comment]
My quick benchmarks show that it is not. But there are bug reports which say that even doing a query using `LIMIT 1` can cause issues on large datasets. There are also mentions that this should be fixed in the latest version. So I don't really know.

**Comment by mitar** [comment]
OK, the beauty of abstractions is that we can improve this later on if we find that it is a problem. :-)

**Comment by kostko** [comment]
Yes. Datastream has shown itself to be a really nice abstraction, as we are able to switch entire backends without breaking nodewatcher.

**Comment by mitar** [comment]
Opened:
 * https://github.com/influxdata/influxdb/issues/5364
 * https://github.com/influxdata/influxdb/issues/5365
 * https://github.com/influxdata/influxdb/issues/5369

**Comment by kostko** [comment]
NULL values implemented in ba82a8be32cab646390061fde125eb2460d5faf4.

**Comment by mitar** [comment]
Superb! For time downsamples, are you then returning the same value for all time downsamplers? The start of the bucket?

**Comment by kostko** [comment]
> Superb! For time downsamples, are you then returning the same value for all time downsamplers? The start of the bucket?

No, currently the backend declares that only "mean" is implemented and it returns this only value as the mean (as I think that only the mean is used in django-datastream).

**Comment by mitar** [comment]
Yes, only mean is used. But so now we are returning the first timestamp as mean timestamp? Beautiful. :-)

**Pull request merged**
